#!/usr/bin/env ruby
require 'rubygems'
require "opengl"
require 'optparse'
require 'pp'

# parse options
$options = {
	:debug => false,
	:profile => false,
	:scene => "default",
	:port => 2300,
	:peer => {
		:address => false,
		:port => 2300
	},
	:fullscreen => false,
	:width => 640,
	:height => 480
}
OptionParser.new do |opts|
	opts.banner = "Usage: #{$0} [options]"
	opts.on("-h", "--help", "This help"){|v| puts opts; exit 0 }
	opts.on("-s", "--scene SCENE", "Select a scene to load"){|v| $options[:scene] = v }
	opts.on("--profile", "Profile the scene"){|v| $options[:profile] = v }
	opts.on("--port PORT", "Local port to use for networking"){|v| $options[:port] = v }
	opts.on("-f", "--fullscreen", "Run in fullscreen mode"){|v| $options[:fullscreen] = v }
	opts.on("-r", "--res RES", "Resolution <width:height>"){|v| $options[:width],$options[:height] = v.split(":").map{|x|x.to_i} }
	opts.on("-p", "--peer PEER", "Specify the remote peer (host) to connect to"){|v| 
		v =~ /([^:]*):?([0-9]*)?/
		$options[:peer][:address] = $1
		$options[:peer][:port] = $2 unless $2.nil? or $2.empty?
	}
	opts.on("-d", "--debug", "Enable debugging output"){|v|
		$options[:debug] = true
	}
end.parse!

if $options[:debug]
	puts "Command line options:"
	pp $options
end

# defines
ROOT=File.dirname($0)
DATA="#{ROOT}/data"
LIB="#{ROOT}/lib"
SCENES="#{ROOT}/scenes"
PROFILE="#{ROOT}/profile.txt"
SCENE=$options[:scene]
DEBUG=$options[:debug]

# append load paths
$: << LIB

# load libs
# make sure your libs require their own dependencies
Dir["#{LIB}/*"].sort.each{|file| require file }

# profile the scene
# dump profile to file
if $options[:profile]
	require 'ruby-prof'
	RubyProf.start
	at_exit {
		result = RubyProf.stop
		printer = RubyProf::FlatPrinter.new(result)
		file = File.new PROFILE, 'w'
		printer.print(file, 0)
		file.close
		puts "profile saved to #{PROFILE}"
	}
end

# load scene
require "#{SCENES}/#{$options[:scene]}"
